### ISSUE TITLE
Feature-request: eraser shouldn't erase uploaded slide, should only erase what I drew over it

### ISSUE THREAD

**Issue by peey** [LakshyAAAgrawal/CoVid#32]
You might be able to do this by layering: https://stackoverflow.com/a/3008863/1412255

Bonus: put all the points drawn between a `mousedown` and `mouseup` to a single new layer, and trying to erase it (you'll have to maintain extra info about which layer is visible at the top at which pixel) erases the entire layer. Some apps do this, this lets you erase entire characters / lines that you drew at once, instead of tediously tracing it with the eraser.

**Comment by LakshyAAAgrawal** [comment]
This looks very interesting to work upon. Thanks!
