### ISSUE TITLE
MacOS+Chrome: Error importing base pdf

### ISSUE THREAD

**Issue by LakshyAAAgrawal** [LakshyAAAgrawal/CoVid#43]
```
Failed to load resource: net::ERR_INVALID_URL
Uncaught TypeError: Cannot read property 'getDocument' of undefined at FileReader.<anonymous> (decl.js:494)
```

**Comment by LakshyAAAgrawal** [comment]
Might be related to #41

**Comment by LakshyAAAgrawal** [comment]
Probably caused by a Chrome extension like Adblock-plus blocking the library from loading

**Comment by nahimilega** [comment]
> Probably caused by a Chrome extension like Adblock-plus blocking the library from loading

I think this might not be the case, I was able to reproduce the bug in a temporary profile of chromium browser. A temporary profile is like installing a new instance of the browser, without any extensions.

**Comment by LakshyAAAgrawal** [comment]
Then I believe the solution is to make the library a part of our
repository, in the hope that whatever is blocking the library from loading
will not block our own (github) server.
